### ISSUE TITLE
Add more default instrument types

### ISSUE THREAD

**Issue by jamesa08** [jamesa08/MIDIAnimator#16]
probably just Hi-Hat animation for now- more in the future.

**Comment by orangeisbetter** [comment]
Is this still in development? I've been working on a MIDI animation in blender and it's taking a while with animation nodes. I'm just curious to see how this develops and what people can do with it.

**Comment by jamesa08** [comment]
> Is this still in development? I've been working on a MIDI animation in blender and it's taking a while with animation nodes. I'm just curious to see how this develops and what people can do with it.

This project is still in development, but you can use it. Eventually it'll hopefully look a little nicer with a custom nodes system but that's a little ways away!
